drop user abTest cascade;

CREATE USER ABTEST  IDENTIFIED BY abTest
  DEFAULT TABLESPACE ADRESBESTAND_TS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for ABTEST
  GRANT DEVELOPER_ACCESS TO ABTEST;
  GRANT PLUSTRACE TO ABTEST;
  GRANT CREATE ANY PROCEDURE TO ABTEST;
  GRANT CREATE ANY SEQUENCE TO ABTEST;
  GRANT CREATE ANY TABLE TO ABTEST;
  GRANT CREATE ANY VIEW TO ABTEST;
  GRANT CREATE TABLE TO ABTEST;
  GRANT DROP ANY TABLE TO ABTEST;
  GRANT DROP ANY VIEW TO ABTEST;
  GRANT EXECUTE ANY PROCEDURE TO ABTEST;
  GRANT SELECT ANY SEQUENCE TO ABTEST;
  GRANT SELECT ANY TABLE TO ABTEST;
  GRANT CREATE ANY SYNONYM TO ABTEST;
  GRANT CREATE SESSION to ABTEST;

  ALTER USER ABTEST DEFAULT ROLE ALL;
  -- 5 System Privileges for ABTEST
  GRANT CREATE SYNONYM TO ABTEST;
  GRANT CREATE MATERIALIZED VIEW TO ABTEST;
  GRANT CREATE JOB TO ABTEST;
  GRANT DEBUG ANY PROCEDURE TO ABTEST;
  GRANT DEBUG CONNECT SESSION TO ABTEST;
  -- 8 Tablespace Quotas for ABTEST
  ALTER USER ABTEST QUOTA UNLIMITED ON ADRESBESTAND_TS;