drop tablespace adresbestand_ts including contents and datafiles;

CREATE TABLESPACE ADRESBESTAND_TS DATAFILE 
  'D:\javadev\oraclexe\app\oracle\oradata\XE\ADRESBESTAND_TS.dbf' SIZE 70M AUTOEXTEND ON NEXT 20M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;