-- INSERT INTO MUNICIPALITY (ID,ZIPCODE, CITY) values(100,1000,'Brussel');
-- INSERT INTO MUNICIPALITY (ID,ZIPCODE, CITY) values(101,1060,'Sint-Gillis');
-- INSERT INTO MUNICIPALITY (ID,ZIPCODE, CITY) values(102,1080,'Anderlecht');
--INSERT INTO MUNICIPALITY (ID,ZIPCODE, CITY) values(103,1040,'Etterbeek');


insert into ADDRESS (ID, STREET, HOUSENUMBER, MUNICIPALITY_ID) VALUES  (50, 'Wetstraat', '105', 103);

insert into PERSON (LAST_NAME, FIRST_NAME, ADDRESS_ID) VALUES  ('De Wever', 'Bart', 50);
