CREATE TABLE MUNICIPALITY (
	ID NUMBER(10,0) NOT NULL,
	ZIPCODE NUMBER (4) NOT NULL,
	CITY VARCHAR2(100 BYTE) NOT NULL
	)
TABLESPACE ADRESBESTAND_TS;

-- add Primary keys --
ALTER TABLE MUNICIPALITY ADD (CONSTRAINT PK_MUNICIPALITY PRIMARY KEY  (ID)
USING INDEX  TABLESPACE ADRESBESTAND_TS);

--- add sequences --
CREATE SEQUENCE MUNICIPALITY_S
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
 	NOMINVALUE
 	NOCYCLE;

