
ALTER TABLE ADDRESS DROP (CITY, ZIPCODE);


ALTER TABLE ADDRESS ADD MUNICIPALITY_ID INT(10) NOT NULL;


ALTER TABLE ADDRESS
	ADD FOREIGN KEY (ID) REFERENCES MUNICIPALITY (ID);


ALTER TABLE ADDRESS
 ADD CONSTRAINT UNIQUE(STREET, HOUSENUMBER, BOX, MUNICIPALITY_ID);