--DROP UNIQUE CONSTRAINT
ALTER TABLE ADDRESS
  DROP CONSTRAINT addressUniqueConstraint;

-- DROP 2 columns
ALTER TABLE ADDRESS
DROP (CITY, ZIPCODE);

-- ADD new column
ALTER TABLE ADDRESS ADD
  MUNICIPALITY_ID NUMBER(10,0) NOT NULL;

-- add Foreign keys --
ALTER TABLE ADDRESS
	ADD (CONSTRAINT FK_ADDRESS_MUNICIPALITY_ID FOREIGN KEY (ID)
	  REFERENCES MUNICIPALITY (ID));

-- add unique keys --
ALTER TABLE ADDRESS
  ADD CONSTRAINT addressUniqueConstraint UNIQUE(STREET, HOUSENUMBER, BOX, MUNICIPALITY_ID);