CREATE TABLE PERSON_EMAILS (
	PERSON_ID NUMBER(10,0) NOT NULL,
	EMAIL VARCHAR2(250 BYTE) NOT NULL
	)
TABLESPACE ADRESBESTAND_TS;

-- add Primary keys --
ALTER TABLE PERSON_EMAILS ADD (CONSTRAINT PK_PERSON_EMAILS PRIMARY KEY  (PERSON_ID, EMAIL)
USING INDEX  TABLESPACE ADRESBESTAND_TS);

-- add Foreign keys --
ALTER TABLE PERSON_EMAILS
	ADD (CONSTRAINT FK_PERSON_EMAILS_ID FOREIGN KEY (PERSON_ID)
	  REFERENCES PERSON (ID));